# Generated by Django 5.0.1 on 2024-01-25 12:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_remove_actor_user_remove_director_user_actor_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('discussion_id', models.AutoField(primary_key=True, serialize=False, verbose_name='discussion_id')),
                ('topic', models.CharField(blank=True, max_length=255, null=True, verbose_name='topic')),
                ('posts', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'discussion',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False, verbose_name='movie_id')),
                ('title', models.CharField(max_length=150, null=True, verbose_name='movie_title')),
                ('plot', models.TextField(blank=True, max_length=5000, verbose_name='plot')),
                ('release_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2024)], verbose_name='movie release year')),
                ('poster_image', models.ImageField(upload_to='posters/')),
                ('actors', models.ManyToManyField(to='users.actor')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directed_movies', to='users.director')),
            ],
            options={
                'verbose_name': 'movie',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.TextField(blank=True, max_length=5000, verbose_name='post text')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_posts', to='movies.discussion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'post',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False, verbose_name='movie_review_id')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='movie_rating')),
                ('comment', models.TextField(blank=True, max_length=5000, verbose_name='comment for movie')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'review',
            },
        ),
    ]
