# Generated by Django 5.0.1 on 2024-01-25 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=5000, verbose_name='text of comment for movie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True, verbose_name='movie title')),
                ('plot', models.TextField(blank=True, max_length=5000, verbose_name='plot')),
                ('release_year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2024)], verbose_name='movie release year')),
                ('poster_image', models.ImageField(upload_to='posters/')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='movie rating')),
                ('text', models.TextField(blank=True, max_length=5000, verbose_name='text of review for movie')),
            ],
        ),
    ]
